In [1]:
import numpy as np

In [2]:
narr = np.random.randint(10, size=(5,4))
print(narr)

[[1 9 1 3]
 [8 5 9 3]
 [5 6 8 0]
 [4 9 5 8]
 [2 2 9 0]]


## SUM

In [3]:
total_sum = narr.sum() #total sum of all rows and columns
print(total_sum)

97


In [4]:
column_sum = narr.sum(axis=0) #sum per column
print(column_sum)

[20 31 32 14]


In [5]:
row_sum = narr.sum(axis=1) #sum per row
print(row_sum)

[14 25 19 26 13]


## Mean and Median


In [6]:
col_mean = narr.mean(axis=0)
print(col_mean)

row_mean = narr.mean(axis=1)
print(row_mean)

[4.  6.2 6.4 2.8]
[3.5  6.25 4.75 6.5  3.25]


In [8]:
col_med = np.median(narr,axis=0)
print(col_med)

row_med = np.median(narr,axis=1)
print(row_med)

[4. 6. 8. 3.]
[2.  6.5 5.5 6.5 2. ]


## Standard Deviation and Variance

In [9]:
col_std = np.std(narr, axis=0)
print(col_std)

row_std = np.std(narr, axis=1)
print(row_std)

col_var = np.var(narr, axis=0)
print(col_var)

row_var = np.var(narr, axis=1)
print(row_var)

[2.44948974 2.63818119 3.0724583  2.92574777]
[3.27871926 2.384848   2.94745653 2.06155281 3.41869858]
[6.   6.96 9.44 8.56]
[10.75    5.6875  8.6875  4.25   11.6875]
