# Matrix Arithmetic

In [1]:
import numpy as np

In [2]:
import random

In [3]:
#autogenerated multidimensional numpy array 2*2
np_big_matrix = np.arange(4).reshape(2,2)
print(np_big_matrix)

[[0 1]
 [2 3]]


## Multiplication

In [4]:
#haddmard multiplication
print(np_big_matrix * np_big_matrix)

[[0 1]
 [4 9]]


In [5]:
#Element wise multiplication
print(np.multiply(np_big_matrix,np_big_matrix))

[[0 1]
 [4 9]]


## Inverse

In [6]:
from numpy.linalg import inv

In [7]:
np_big_matrix_inverse = inv(np_big_matrix)
print(np_big_matrix)

[[0 1]
 [2 3]]


## Transpose

In [8]:
print(np_big_matrix.T)

[[0 2]
 [1 3]]


## Solve Equations

In [9]:
#A few rules the number of columns should be the same size
#The large matrix should be a square i.e 2*2, 4*4

a = np.random.randint(10, size=(4,4)) #4 by 4 matrix 
b = np.random.randint(10, size=4) # 4 by 1 matrix

print(a)
print(b)

[[6 4 1 1]
 [1 7 6 6]
 [8 6 2 9]
 [3 4 7 7]]
[1 7 8 0]


In [10]:
#Solve linear equations - method 1
ainv = np.linalg.inv(a)
c = ainv.dot(b)
print(c)

[-0.8079096   1.60451977 -1.42453592  0.85391445]


In [11]:
#Solve linear equations - method 2
c = np.linalg.solve(a,b)
print(c)

[-0.8079096   1.60451977 -1.42453592  0.85391445]
