In [1]:
import numpy as np

In [2]:
import random

In [3]:
x = [1,4,5,6]
y = [23,4,12]

x = np.array(x)
y = np.array(y)

#concatenate two arrays
z = np.concatenate([x, y])

print(z)

[ 1  4  5  6 23  4 12]


In [4]:
#autogenerated multidimensional numpy array 4*4
np_big_arr = np.arange(16).reshape(4,4)
print(np_big_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
#column by row to get value
print(np_big_arr[3,0])
print(np_big_arr[1:3,1:3])

12
[[ 5  6]
 [ 9 10]]


In [6]:
#change a specific value
np_big_arr[3,0]=9
print(np_big_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 9 13 14 15]]
