# Vector Arithmetic

In [1]:
import numpy as np

In [2]:
import random

In [3]:
w = np.array([[5],[1],[7]])
x = np.array([2,5,7])
y = np.array([[3,6,1],[5,9,2]])

## Addition

In [4]:
#numpy array - x
xresult = x + 2
print(xresult)

[4 7 9]


In [5]:
#numpy array - y
yresult = y + 5
print(yresult)

[[ 8 11  6]
 [10 14  7]]


In [6]:
#(3 * 1) + (1 * 3) = (3 * 3)
#print(x)
#print(w)
zresult = x + w
print(zresult)

[[ 7 10 12]
 [ 3  6  8]
 [ 9 12 14]]


## Subtraction

In [7]:
aresult = x - w
bresult = w - x

print(aresult)
print('------------')
print(bresult)

[[-3  0  2]
 [ 1  4  6]
 [-5 -2  0]]
------------
[[ 3  0 -2]
 [-1 -4 -6]
 [ 5  2  0]]


## Multiplication

In [8]:
#hadmond multiplication
cresult = x * w
print(cresult)

[[10 25 35]
 [ 2  5  7]
 [14 35 49]]


In [9]:
#dot product
dresult = np.dot(x,w)
print(dresult)

[64]
